/**
 * Ensures the full Cocos Creator 3.8.4 engine type declarations are visible to
 * `tsc` so that numeric primitive property types `CCFloat` and `CCInteger` are
 * resolvable from the `cc` module.
 *
 * The project's `temp/declarations/cc.d.ts` (generated by Cocos Editor on open)
 * already re-exports the engine types via a `/// <reference>` to the installed
 * engine. That file is intentionally git-ignored and is NOT part of the
 * `tsconfig.game.json` `include` list, so the type-checker otherwise only sees a
 * trimmed ambient `cc` shim that lacks `CCFloat`/`CCInteger`. Pulling it in here
 * makes `import { CCFloat, CCInteger } from 'cc'` type-check correctly without
 * re-declaring or shadowing the engine's own definitions (so there is no
 * `any` and no duplicate-identifier conflict in a full-engine environment).
 *
 * Reference path is relative to this file; it resolves to the Cocos-generated
 * shim which in turn references the real engine `cc.d.ts`.
 */
/// <reference path="../temp/declarations/cc.d.ts" />
