/**
 * OpenAIPlannerProvider — Uses OpenAI API to generate the next development task.
 * Reads project context, phase state, recent reports, and generates a Task JSON.
 */
import fs from 'fs';
import path from 'path';
import { config, dirs, root } from '../config';
import { callOpenAI, parseJSON } from '../openai-client';
import { recordCall } from '../budget-tracker';
import { buildPlannerContext } from '../context-builder';
import { readPhase, phaseSummary } from '../phase-gate';
import { pendingTasks, loadTask } from '../task-loader';
import { validateTask } from '../schema-validator';
import { log } from '../logger';
import {
  PlannerProvider, PlannerContext, PlannerResult,
  Task, TaskStatusSummary, StopReason,
} from '../types';

const SYSTEM_PROMPT_PATH = path.join(dirs.prompts, 'planner-system.md');

function readSystemPrompt(): string {
  if (fs.existsSync(SYSTEM_PROMPT_PATH)) {
    return fs.readFileSync(SYSTEM_PROMPT_PATH, 'utf8');
  }
  return 'You are a task planner. Generate the next development task as JSON.';
}

function getTaskStatusSummaries(): TaskStatusSummary[] {
  const summaries: TaskStatusSummary[] = [];
  const statuses = ['pending', 'running', 'review', 'fixing', 'done', 'failed', 'escalated'] as const;
  for (const status of statuses) {
    const dir = path.join(dirs.tasks, status);
    if (!fs.existsSync(dir)) continue;
    const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));
    for (const file of files.slice(0, 50)) {
      try {
        const task = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8')) as Task;
        summaries.push({
          id: task.id,
          status: task.status,
          priority: task.priority,
          title: task.title,
        });
      } catch { /* skip corrupt */ }
    }
  }
  return summaries;
}

function getRecentReports(): string[] {
  if (!fs.existsSync(dirs.reports)) return [];
  return fs.readdirSync(dirs.reports)
    .filter(f => f.endsWith('.md') && f !== 'LATEST.md')
    .sort()
    .slice(-5);
}

async function getGitLog(): Promise<string> {
  try {
    const { runCommand } = await import('../command-runner');
    const result = await runCommand('git', ['log', '--oneline', '-20'], 'PLANNER');
    return result.success ? result.stdout.trim() : '(git log unavailable)';
  } catch {
    return '(git log unavailable)';
  }
}

export class OpenAIPlannerProvider implements PlannerProvider {
  async planNextTask(context: PlannerContext, signal?: AbortSignal): Promise<PlannerResult> {
    const systemPrompt = readSystemPrompt();
    const phase = context.phase || readPhase();

    // Build rich context
    const taskStatuses = context.taskStatus?.length ? context.taskStatus : getTaskStatusSummaries();
    const recentReports = context.recentReports?.length ? context.recentReports : getRecentReports();
    const gitLog = context.gitLog || await getGitLog();
    const agentsMd = context.agentsMd || '';

    const userContext = buildPlannerContext(
      { currentPhase: phase.currentPhase, status: phase.status },
      recentReports,
      taskStatuses,
    );

    // Add git log
    const fullUserPrompt = `${userContext}\n\n---\n\n# Git Log (recent)\n${gitLog}\n\n---\n\n# Last Review\n${context.lastReview || '(none)'}\n\nGenerate the next task JSON. If no task is needed, output {"stopReason": "NO_TASK"}`;

    const taskId = 'PLANNER';
    log(taskId, `Calling OpenAI Planner with model=${config.openaiModel}`);

    try {
      const result = await callOpenAI({
        model: config.openaiModel,
        systemPrompt,
        userPrompt: fullUserPrompt,
        maxTokens: 4096,
        temperature: 0.3,
        responseFormat: 'json_object',
        taskId,
        timeoutMs: config.plannerTimeoutMs,
      });

      recordCall('openai', config.openaiModel, result.durationMs, result.tokensUsed);

      // Parse the response
      const parsed = parseJSON<PlannerResult>(result.content, taskId);

      // Check for stop reason (no task)
      if (parsed.stopReason) {
        log(taskId, `Planner stop reason: ${parsed.stopReason}`);
        return { task: null, reason: parsed.stopReason, stopReason: parsed.stopReason as StopReason };
      }

      // Validate the generated task
      if (!parsed.task) {
        // Try to interpret the entire response as a task
        const maybeTask = parsed as unknown as Task;
        if (maybeTask.id && maybeTask.title && maybeTask.goal) {
          validateTask(maybeTask);
          return { task: maybeTask, reason: 'Generated by OpenAI Planner' };
        }
        log(taskId, `Planner returned no task and no stopReason`);
        return { task: null, reason: 'NO_TASK', stopReason: 'NO_TASK' };
      }

      // Validate task schema
      try {
        validateTask(parsed.task);
      } catch (e) {
        log(taskId, `Planner task schema invalid: ${e}`);
        return { task: null, reason: `INVALID_TASK: ${e}`, stopReason: 'ERROR' };
      }

      log(taskId, `Planner generated task: ${parsed.task.id} — ${parsed.task.title}`);
      return { task: parsed.task, reason: parsed.reason || 'Generated by OpenAI Planner' };

    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      log(taskId, `Planner error: ${msg}`);
      if (msg.includes('OPENAI_MODEL_UNAVAILABLE')) {
        return { task: null, reason: 'OPENAI_MODEL_UNAVAILABLE', stopReason: 'OPENAI_UNAVAILABLE' };
      }
      throw error;
    }
  }
}